language: node_js
node_js:
  - "stable"
notifications:
  email: false
cache:
  directories:
    - node_modules
before_install:
  - npm install -g npm@latest
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
